const computerTerms = {
    ALGORITHM: "A process or set of rules to be followed in calculations or other problem-solving operations, especially by a computer.",
    API: "Application Programming Interface, a set of rules that allow different software entities to communicate.",
    ARRAY: "A data structure that stores elements of the same type in a sequential manner.",
    ASCII: "American Standard Code for Information Interchange, a character encoding standard for text.",
    ASYNCHRONOUS: "Operations that occur independently of the main program flow.",
    AUTHENTICATION: "The process of verifying a user’s identity.",
    BACKUP: "A copy of data stored separately for recovery in case of data loss.",
    BANDWIDTH: "The maximum data transfer rate of a network or internet connection.",
    BIOS: "Basic Input/Output System, firmware for hardware initialization during booting.",
    BIT: "The smallest unit of data in computing, representing a binary value of 0 or 1.",
    BLOCKCHAIN: "A decentralized digital ledger for recording transactions securely.",
    BOOTLOADER: "A program that starts the operating system on a computer.",
    BYTE: "A unit of digital information that typically consists of 8 bits.",
    CACHE: "A high-speed storage layer that stores frequently accessed data for quick retrieval.",
    CAPTCHA: "A challenge-response test to determine whether a user is human.",
    CLASS: "A blueprint for creating objects in object-oriented programming.",
    CLOUDCOMPUTING: "Internet-based computing that provides shared resources and data.",
    CODE: "In computer programming, computer code refers to the set of instructions, or a system of rules, written in a particular programming language.",
    COMMANDLINE: "A text-based interface for interacting with an operating system or software.",
    COMPILER: "A program that translates high-level source code into machine code.",
    CPU: "Central Processing Unit, the primary component that executes instructions in a computer.",
    CSS: "Cascading Style Sheets, a language used for styling web pages.",
    DATABASE: "An organized collection of data that can be accessed and managed electronically.",
    DEBUGGING: "The process of identifying and fixing errors in software or hardware.",
    DEBUG: "The process of identifying and removing errors from computer hardware or software.",
    DHCP: "Dynamic Host Configuration Protocol, used to assign IP addresses automatically.",
    DNS: "Domain Name System, which converts human-readable domain names into IP addresses.",
    DOCKER: "A platform for developing, shipping, and running containerized applications.",
    ECOMMERCE: "Buying and selling goods or services over the internet.",
    ENCRYPTION: "The process of converting information into a secure code to prevent unauthorized access.",
    ETHERNET: "A wired networking technology for local area networks.",
    FIREWALL: "A network security device that monitors and controls incoming and outgoing traffic.",
    FIRMWARE: "Low-level software that is embedded into hardware devices.",
    FRAMEWORK: "A pre-built structure for building software applications.",
    GITHUB: "A web-based platform used for version control and collaborative software development.",
    GIT: "A distributed version control system for tracking changes in code.",
    GPU: "Graphics Processing Unit, hardware specialized for rendering images and video.",
    HARDDRIVE: "A data storage device used for storing and retrieving digital information.",
    HTML: "HyperText Markup Language, the standard language for creating web pages.",
    HTTP: "HyperText Transfer Protocol, used for transferring data over the web.",
    HTTPS: "Secure HyperText Transfer Protocol, an encrypted version of HTTP.",
    IDE: "Integrated Development Environment, a software suite for programming.",
    INTERNET: "A global network of interconnected devices for communication and data sharing.",
    IPADDRESS: "A unique numerical label assigned to devices on a network.",
    JAVA: "A programming language designed for creating platform-independent applications.",
    JSON: "JavaScript Object Notation, a lightweight format for storing and transporting data.",
    KERNEL: "The core part of an operating system that manages system resources.",
    KEYLOGGER: "A tool that records every keystroke made on a device.",
    LAN: "Local Area Network, a network of connected devices within a limited area.",
    LINUX: "An open-source operating system based on the UNIX architecture.",
    LOADBALANCER: "A device or software that distributes network or application traffic across servers.",
    MACHINELEARNING: "A subset of AI where systems learn from data and improve without explicit programming.",
    MACADDRESS: "A hardware address assigned to network devices for communication.",
    MALWARE: "Software that is specifically designed to disrupt, damage, or gain unauthorized access to a computer system.",
    NETWORK: "A group of interconnected devices for sharing resources and information.",
    NODE: "A single device or point in a network.",
    NFT: "Non-Fungible Token, a unique digital asset verified using blockchain.",
    OBJECTORIENTEDPROGRAMMING: "A programming paradigm based on objects containing data and methods.",
    OOP: "A programming paradigm based on objects containing data and methods.",
    OPERATINGSYSTEM: "System software that manages hardware and software resources.",
    OS: "System software that manages hardware and software resources.",
    OPENSOURCE: "Software with publicly available source code that can be modified and shared.",
    PACKET: "A unit of data transmitted over a network.",
    PHISHING: "A fraudulent attempt to obtain sensitive information by disguising as a trustworthy entity.",
    PYTHON: "A high-level programming language known for its readability and versatility.",
    QUERY: "A request for information or data from a database.",
    QRCODE: "A machine-readable code for storing and retrieving information.",
    RAM: "Random Access Memory, temporary storage for data currently in use.",
    ROUTER: "A device that forwards data packets between computer networks, directing traffic on the internet.",
    SCRIPT: "A series of instructions written for a specific task.",
    SERVER: "A computer or system that provides resources, data, services, or programs to other computers, known as clients, over a network.",
    SOFTWARE: "Programs and operating information used by a computer.",
    SPAM: "Unsolicited and irrelevant messages sent online.",
    SQL: "Structured Query Language, used for managing data in relational databases.",
    SSL: "Secure Sockets Layer, a protocol for secure communication over the internet.",
    TERABYTE: "A unit of digital storage equivalent to 1,024 gigabytes.",
    THREAD: "A sequence of executable instructions within a program.",
    TROJANHORSE: "Malware disguised as legitimate software.",
    TROJAN: "A type of malware that disguises itself as legitimate software but performs malicious actions once installed.",
    UI: "User Interface, the part of software or hardware that interacts with users.",
    USB: "Universal Serial Bus, a standard for connecting peripherals to computers.",
    VIRTUALMACHINE: "Software emulating a physical computer system.",
    VIRUS: "A type of malicious software that replicates itself and spreads to other computers, often causing harm to systems and data.",
    VPN: "Virtual Private Network, encrypts internet connections for security and privacy.",
    WEBBROWSER: "Software for accessing and viewing websites.",
    WEB: "Software for accessing and viewing websites.",
    WEBSITE: "A collection of web pages accessible via the internet.",
    WIFI: "A technology that allows electronic devices to connect to a wireless local area network (WLAN), typically using radio waves.",
    XML: "Extensible Markup Language, a flexible way to structure data.",
    XSS: "Cross-Site Scripting, a web security vulnerability.",
    YOTTABYTE: "A unit of digital data storage equal to 1,024 zettabytes.",
    ZIP: "A compressed file format for reducing file size.",
    ZETTABYTE: "A unit of data storage equal to 1,024 exabytes.",
    ACCESSCONTROL: "A security technique that regulates who or what can view or use resources in a computing environment.",
    AGILE: "A methodology in software development that promotes iterative development, collaboration, and flexibility in the process.",
    AI: "Artificial Intelligence, the simulation of human intelligence in machines that are programmed to think and learn.",
    ALIAS: "A shortcut or an alternative name used for a file, command, or object.",
    ANDROID: "An open-source operating system primarily used for mobile devices, such as smartphones and tablets.",
    APP: "Short for application, a software program designed to perform specific tasks for the user.",
    ARCHITECTURE: "The structure of a computer system, including its hardware and software components.",
    ARTIFICIALNEURALNETWORK: "A model used in machine learning that mimics the way biological neural networks in the human brain process information.",
    BIGDATA: "Large, complex datasets that are difficult to process with traditional data management tools.",
    BLOCK: "A group of data stored together in a blockchain system that is securely linked to the previous block.",
    BRUTEFORCEATTACK: "A type of cyberattack where an attacker tries all possible combinations to guess passwords or encryption keys.",
    BROWSER: "A software application used to access and view websites.",
    BYTECODE: "An intermediate code produced by a compiler that can be executed by a virtual machine, often used in Java.",
    CACHEMISS: "Occurs when the requested data is not found in the cache, leading to a slower data retrieval process.",
    CIRCUIT: "An electrical system that connects components to enable the flow of electricity and execute tasks in a computer.",
    CLOUDSTORAGE: "A service that allows you to store data on remote servers, accessible via the internet.",
    CONTAINER: "A lightweight, portable environment for running applications, which includes everything the application needs to run, including libraries and settings.",
    COOKIES: "Small pieces of data sent by websites to your browser for storing information between sessions.",
    CRYPTOCURRENCY: "A digital or virtual currency that uses cryptography for security, with decentralized control, typically based on blockchain technology.",
    CYBERSECURITY: "The practice of defending computers, networks, and data from malicious attacks or unauthorized access.",
    DATALAKE: "A centralized repository for storing vast amounts of raw data in its native format.",
    DEVOPS: "A set of practices that combine software development (Dev) and IT operations (Ops) to shorten the systems development lifecycle and provide continuous delivery with high software quality.",
    DICTIONARYATTACK: "A type of cyberattack that uses a list of common words or phrases to guess passwords or encryption keys.",
    DNSSEC: "Domain Name System Security Extensions, a suite of extensions to DNS that add an additional layer of security to protect against certain attacks.",
    DUALBOOT: "A system setup where two operating systems are installed on the same computer, and users can choose which one to boot into.",
    EDGECOMPUTING: "A distributed computing paradigm that brings computation and data storage closer to the location where it is needed, improving response times and saving bandwidth.",
    ENDPONT: "Any device or node that communicates over a network, such as a computer, smartphone, or printer.",
    ENTERPRISE: "Large-scale organizations that utilize complex computing systems and software solutions to support business operations.",
    EXPLOIT: "A piece of software, a chunk of data, or a sequence of commands that take advantage of a bug or vulnerability in a system.",
    FIREWALLRULES: "Configurations used to define what type of traffic is allowed or denied by a firewall.",
    FOGCOMPUTING: "A decentralized computing infrastructure that extends cloud computing capabilities to the edge of a network to enable faster data processing.",
    GADGET: "A small electronic device, such as a smartphone, tablet, or smart speaker, that typically performs specific functions.",
    GIGABIT: "A unit of digital information equal to one billion bits, often used to describe network speeds.",
    GROWTHHACKING: "A marketing strategy that uses creativity, analytics, and social metrics to gain exposure and scale quickly.",
    HASHING: "A process used to transform data into a fixed-size string of characters, typically for indexing or data verification.",
    HACKER: "A person skilled in computer systems and programming, who may use their abilities for malicious or ethical purposes.",
    IOT: "Internet of Things, the network of physical devices connected to the internet to collect and exchange data.",
    LATENCY: "The time delay between the initiation of a request and the completion of the corresponding action in a system.",
    MACHINEVIRTUALIZATION: "The process of creating virtual versions of physical machines or hardware resources to optimize utilization and manageability.",
    MALWAREANALYSIS: "The process of examining malicious software to understand its behavior and develop strategies for detecting and defending against it.",
    METADATA: "Data that describes other data, often used to summarize information about content or describe the structure of data.",
    NAT: "Network Address Translation, a method used by routers to modify IP address information in IP packet headers.",
    NOC: "Network Operations Center, a centralized location where IT professionals monitor, manage, and maintain network infrastructure.",
    PATCH: "A piece of software designed to update or fix issues with a program or operating system.",
    PRIVACYPOLICY: "A legal document that explains how an organization collects, uses, and protects user data.",
    QUANTUMCOMPUTING: "A new field of computing that utilizes quantum-mechanical phenomena to perform computations in ways that classical computers cannot.",
    RANSOMWARE: "A type of malware that encrypts a user’s data and demands payment to restore access.",
    REPOSITORY: "A centralized location where code, files, or data are stored and managed, often used in version control systems.",
    RESILIENCE: "The ability of a system to recover from disruptions and continue functioning.",
    RPA: "Robotic Process Automation, the use of software robots to automate repetitive tasks in business processes.",
    SDK: "Software Development Kit, a set of tools and libraries that developers use to create applications for a specific platform.",
    SCALABILITY: "The ability of a system to handle an increasing amount of work or to be easily expanded to accommodate growth.",
    SCRUM: "An agile framework for managing and completing complex projects through iterative and incremental work cycles.",
    SCRIPTINGLANGUAGE: "A programming language used for writing scripts that automate tasks, often used in web development or system administration.",
    SEO: "Search Engine Optimization, the process of optimizing web content to improve its ranking in search engine results.",
    SHA: "Secure Hash Algorithm, a cryptographic hash function used to secure data and verify its integrity.",
    SIMULATION: "The process of modeling a real-world process or system to study its behavior or predict outcomes.",
    SMARTCONTRACT: "A self-executing contract with the terms of the agreement directly written into code, typically used on blockchain platforms.",
    SNMP: "Simple Network Management Protocol, used to manage and monitor networked devices.",
    SQLINJECTION: "A web security vulnerability that allows attackers to interfere with the queries made to a database.",
    SSLVPN: "A Virtual Private Network that uses Secure Sockets Layer encryption to secure communications over the internet.",
    SYNCHRONIZATION: "The process of ensuring that data is consistent across different devices or systems at the same time.",
    TOKENIZATION: "The process of replacing sensitive data with a unique identifier, or token, that is not sensitive but can be mapped back to the original data.",
    UIUX: "User Interface (UI) and User Experience (UX), design principles focused on improving how users interact with software and how they feel about it.",
    V2V: "Vehicle-to-Vehicle communication, a technology that allows vehicles to exchange data to improve safety and traffic efficiency.",
    VERSIONCONTROL: "A system that tracks changes to files, usually source code, allowing for collaboration and change management in software development.",
    VIRTUALIZATION: "The creation of virtual versions of physical devices, such as servers, storage devices, or networks, to optimize efficiency and resource utilization.",
    VOIP: "Voice Over Internet Protocol, a technology that allows voice communication to be transmitted over the internet.",
    WEBRTC: "Web Real-Time Communication, a technology that enables peer-to-peer communication directly between web browsers without the need for plugins.",
    XBLOCKCHAIN: "A decentralized system where transactions are recorded securely and verifiably using a blockchain, but typically in non-financial applications.",
    YOCTOBYTE: "A unit of digital data storage equal to 1,024 zettabytes."
};

export default computerTerms;