const computerTerms = {
    ALGORITHM: "A process or set of rules to be followed in calculations or other problem-solving operations, especially by a computer.",
    API: "Application Programming Interface, a set of rules that allow different software entities to communicate.",
    ARRAY: "A data structure that stores elements of the same type in a sequential manner.",
    ASCII: "American Standard Code for Information Interchange, a character encoding standard for text.",
    ASYNCHRONOUS: "Operations that occur independently of the main program flow.",
    AUTHENTICATION: "The process of verifying a user’s identity.",
    BACKUP: "A copy of data stored separately for recovery in case of data loss.",
    BANDWIDTH: "The maximum data transfer rate of a network or internet connection.",
    BIOS: "Basic Input/Output System, firmware for hardware initialization during booting.",
    BIT: "The smallest unit of data in computing, representing a binary value of 0 or 1.",
    BLOCKCHAIN: "A decentralized digital ledger for recording transactions securely.",
    BOOTLOADER: "A program that starts the operating system on a computer.",
    BYTE: "A unit of digital information that typically consists of 8 bits.",
    CACHE: "A high-speed storage layer that stores frequently accessed data for quick retrieval.",
    CAPTCHA: "A challenge-response test to determine whether a user is human.",
    CLASS: "A blueprint for creating objects in object-oriented programming.",
    CLOUDCOMPUTING: "Internet-based computing that provides shared resources and data.",
    CODE: "In computer programming, computer code refers to the set of instructions, or a system of rules, written in a particular programming language.",
    COMMANDLINE: "A text-based interface for interacting with an operating system or software.",
    COMPILER: "A program that translates high-level source code into machine code.",
    CPU: "Central Processing Unit, the primary component that executes instructions in a computer.",
    CSS: "Cascading Style Sheets, a language used for styling web pages.",
    DATABASE: "An organized collection of data that can be accessed and managed electronically.",
    DEBUGGING: "The process of identifying and fixing errors in software or hardware.",
    DEBUG: "The process of identifying and removing errors from computer hardware or software.",
    DHCP: "Dynamic Host Configuration Protocol, used to assign IP addresses automatically.",
    DNS: "Domain Name System, which converts human-readable domain names into IP addresses.",
    DOCKER: "A platform for developing, shipping, and running containerized applications.",
    ECOMMERCE: "Buying and selling goods or services over the internet.",
    ENCRYPTION: "The process of converting information into a secure code to prevent unauthorized access.",
    ETHERNET: "A wired networking technology for local area networks.",
    FIREWALL: "A network security device that monitors and controls incoming and outgoing traffic.",
    FIRMWARE: "Low-level software that is embedded into hardware devices.",
    FRAMEWORK: "A pre-built structure for building software applications.",
    GITHUB: "A web-based platform used for version control and collaborative software development.",
    GIT: "A distributed version control system for tracking changes in code.",
    GPU: "Graphics Processing Unit, hardware specialized for rendering images and video.",
    HARDDRIVE: "A data storage device used for storing and retrieving digital information.",
    HTML: "HyperText Markup Language, the standard language for creating web pages.",
    HTTP: "HyperText Transfer Protocol, used for transferring data over the web.",
    HTTPS: "Secure HyperText Transfer Protocol, an encrypted version of HTTP.",
    IDE: "Integrated Development Environment, a software suite for programming.",
    INTERNET: "A global network of interconnected devices for communication and data sharing.",
    IPADDRESS: "A unique numerical label assigned to devices on a network.",
    JAVA: "A programming language designed for creating platform-independent applications.",
    JSON: "JavaScript Object Notation, a lightweight format for storing and transporting data.",
    KERNEL: "The core part of an operating system that manages system resources.",
    KEYLOGGER: "A tool that records every keystroke made on a device.",
    LAN: "Local Area Network, a network of connected devices within a limited area.",
    LINUX: "An open-source operating system based on the UNIX architecture.",
    LOADBALANCER: "A device or software that distributes network or application traffic across servers.",
    MACHINELEARNING: "A subset of AI where systems learn from data and improve without explicit programming.",
    MACADDRESS: "A hardware address assigned to network devices for communication.",
    MALWARE: "Software that is specifically designed to disrupt, damage, or gain unauthorized access to a computer system.",
    NETWORK: "A group of interconnected devices for sharing resources and information.",
    NODE: "A single device or point in a network.",
    NFT: "Non-Fungible Token, a unique digital asset verified using blockchain.",
    OBJECTORIENTEDPROGRAMMING: "A programming paradigm based on objects containing data and methods.",
    OOP: "A programming paradigm based on objects containing data and methods.",
    OPERATINGSYSTEM: "System software that manages hardware and software resources.",
    OS: "System software that manages hardware and software resources.",
    OPENSOURCE: "Software with publicly available source code that can be modified and shared.",
    PACKET: "A unit of data transmitted over a network.",
    PHISHING: "A fraudulent attempt to obtain sensitive information by disguising as a trustworthy entity.",
    PYTHON: "A high-level programming language known for its readability and versatility.",
    QUERY: "A request for information or data from a database.",
    QRCODE: "A machine-readable code for storing and retrieving information.",
    RAM: "Random Access Memory, temporary storage for data currently in use.",
    ROUTER: "A device that forwards data packets between computer networks, directing traffic on the internet.",
    SCRIPT: "A series of instructions written for a specific task.",
    SERVER: "A computer or system that provides resources, data, services, or programs to other computers, known as clients, over a network.",
    SOFTWARE: "Programs and operating information used by a computer.",
    SPAM: "Unsolicited and irrelevant messages sent online.",
    SQL: "Structured Query Language, used for managing data in relational databases.",
    SSL: "Secure Sockets Layer, a protocol for secure communication over the internet.",
    TERABYTE: "A unit of digital storage equivalent to 1,024 gigabytes.",
    THREAD: "A sequence of executable instructions within a program.",
    TROJANHORSE: "Malware disguised as legitimate software.",
    TROJAN: "A type of malware that disguises itself as legitimate software but performs malicious actions once installed.",
    UI: "User Interface, the part of software or hardware that interacts with users.",
    USB: "Universal Serial Bus, a standard for connecting peripherals to computers.",
    VIRTUALMACHINE: "Software emulating a physical computer system.",
    VIRUS: "A type of malicious software that replicates itself and spreads to other computers, often causing harm to systems and data.",
    VPN: "Virtual Private Network, encrypts internet connections for security and privacy.",
    WEBBROWSER: "Software for accessing and viewing websites.",
    WEB: "Software for accessing and viewing websites.",
    WEBSITE: "A collection of web pages accessible via the internet.",
    WIFI: "A technology that allows electronic devices to connect to a wireless local area network (WLAN), typically using radio waves.",
    XML: "Extensible Markup Language, a flexible way to structure data.",
    XSS: "Cross-Site Scripting, a web security vulnerability.",
    YOTTABYTE: "A unit of digital data storage equal to 1,024 zettabytes.",
    ZIP: "A compressed file format for reducing file size.",
    ZETTABYTE: "A unit of data storage equal to 1,024 exabytes."
};

export default computerTerms;