const scienceTerms = {

    // Physics - Mechanics

ACCELERATION: "The rate of change of velocity over time. Formula: a = Δv/Δt",
ACID: "Substance that produces H+ ions in solution",
AMPLITUDE: "Maximum displacement from equilibrium position",
ANTIMATTER: "Matter with opposite properties of normal matter",
ASTEROID: "Rocky object orbiting the Sun",
ATMOSPHERE: "Gaseous layer surrounding Earth",
ATOM: "The basic unit of matter, made up of protons, neutrons, and electrons",
BASE: "Substance that produces OH- ions in solution",
BIOSPHERE: "All life on Earth",
BLACKHOLE: "Region where gravity prevents light escape",
BOND: "Force holding atoms together in molecules",
CARNOT: "Ideal heat engine cycle efficiency. Formula: η = 1 - Tc/Th",
CATALYST: "Substance that speeds up a reaction without being consumed",
CELL: "Basic unit of life",
CENTRIPETAL: "Force directing motion in circular path. Formula: F = mv²/r",
CHROMOSOME: "Structure containing DNA",
CLIMATE: "Long-term weather patterns",
COMET: "Icy body that produces gas tail near Sun",
COMPOUND: "Substance made of different elements chemically combined",
CONDUCTION: "Heat transfer through direct contact",
CONVECTION: "Heat transfer through fluid movement",
DENSITY: "Mass per unit volume of a substance. Formula: ρ = m/V",
DIFFRACTION: "Bending of waves around obstacles",
DNA: "Molecule carrying genetic instructions",
DOPPLER: "Change in wave frequency due to relative motion",
ELECTRON: "Negatively charged particle in atoms",
ELASTICITY: "Property of returning to original shape after deformation",
ELEMENT: "Pure substance made of one type of atom",
ENERGY: "The ability to do work or cause change. It can't be created or destroyed, only transformed",
ENTANGLEMENT: "Quantum correlation between particles",
ENTRAPY: "Measure of disorder in a system. Formula: ΔS = Q/T",
ENZMYE: "Protein that catalyzes biological reactions",
EROSION: "Process of wearing away Earth's surface",
FORCE: "A push or pull that can change an object's motion or shape. Formula: F = ma",
FREQUENCY: "Wave cycles per second. Formula: f = 1/T",
FRICTION: "Force that opposes motion between surfaces in contact",
GALAXY: "Large system of stars bound by gravity",
GENE: "Unit of heredity",
GRAVITY: "The force of attraction between all masses in the universe. Formula: F = G(m₁m₂)/r²",
HEAT: "Transfer of thermal energy between objects",
HEATCAPACITY: "Heat needed to raise temperature by one degree",
HYDROSPHERE: "All water on Earth",
INERTIA: "The resistance of an object to changes in its state of motion",
INTERFERENCE: "Combination of waves to form resultant wave",
LATENT: "Heat absorbed/released during phase change",
LIGHT: "Electromagnetic radiation visible to human eye",
LITHOSPHERE: "Rigid outer part of Earth",
MEMBRANE: "Barrier around cells and organelles",
METEOR: "Space rock burning in Earth's atmosphere",
MINERAL: "Naturally occurring inorganic solid",
MITOSIS: "Cell division for growth and repair",
MOLECULE: "Group of atoms bonded together",
MOMENTUM: "The quantity of motion of a moving body. Formula: p = mv",
NUCLEARREACTION: "Process changing atomic nuclei structure",
NUCLEUS: "Control center of the cell",
NEBULA: "Cloud of gas and dust where stars form",
NEUTRON: "Neutral particle in atomic nuclei",
OPTICS: "Study of light behavior and properties",
PARTICLEPHYSICS: "Study of fundamental particles and interactions",
PLANCK: "Quantum of action in physics. Formula: E = hf",
PLANET: "Celestial body orbiting a star",
POLARIZATION: "Restriction of wave oscillation to one plane",
PRESSURE: "Force applied per unit area. Formula: P = F/A",
PROTEIN: "Large molecules essential for life processes",
PROTON: "Positively charged particle in atomic nuclei",
PULSAR: "Rotating neutron star emitting radiation",
QUANTUM: "Smallest possible discrete unit of any physical property",
QUASAR: "Very bright galactic nucleus",
RADATION: "Heat transfer through electromagnetic waves",
REACTION: "Process where substances change into new substances",
REDSHIFT: "Wavelength increase from moving objects",
REFLECTION: "Bouncing back of waves from a surface",
REFRACTION: "Bending of waves passing between media",
RELATIVITY: "Einstein's theory relating space, time, mass, and energy",
RNA: "Molecule involved in protein synthesis",
SOLUTION: "Homogeneous mixture of substances",
SUPERPOSITION: "Quantum state existing in multiple states simultaneously",
SUPERNOVA: "Explosive death of massive star",
TEMPERATURE: "Measure of average kinetic energy of particles",
THERMODYNAMICS: "Study of heat, energy, and their relationships",
TORQUE: "Rotational force. Formula: τ = r × F",
UNCERTAINTY: "Heisenberg's principle of position-momentum uncertainty",
VELOCITY: "The speed of an object in a specific direction. Formula: v = Δx/Δt",
WAVES: "A disturbance that transfers energy through matter or space",
WAVELENGTH: "Distance between wave peaks. Formula: λ = v/f",
WEATHER: "Short-term atmospheric conditions",
WORK: "The transfer of energy when a force moves an object. Formula: W = Fd",

//Chemistry Dictionary

Aerobic: "Depending on oxygen for survival or function.",
Agglutination: "The clumping of particles, such as blood cells or bacteria, in response to an antibody-antigen reaction.",
Albino: "A person with a congenital absence of pigmentation in the skin, eyes, and hair.",
Allele: "One of two or more alternative forms of a gene that occupy the same position on homologous chromosomes.",
Anaerobic: "Requiring the absence of or not dependent on oxygen for survival or function.",
Anterior: "Located near or toward the head of an organism.",
Asexual: "A form of reproduction that does not involve the fusion of male and female gametes.",
Assimilation: "The process of converting digested food into protoplasm in an organism.",
Bacteria: "Single-celled microorganisms that lack a nucleus and can be found in various environments.",
BinaryFission: "A form of asexual reproduction in which a single cell divides into two identical daughter cells.",
Biomass: "The total mass of living organisms in a given area or ecosystem.",
Blood: "A fluid that circulates through the body, supplying oxygen and nutrients while removing waste products.",
BloodVessel: "A tubular structure that carries blood throughout the body (artery, vein, or capillary).",
Bone: "A rigid structure that makes up the skeleton of most vertebrates.",
Cell: "The basic structural and functional unit of life in all living organisms.",
Chromosome: "A thread-like structure of DNA that contains genetic information.",
Circulation: "The movement of blood through the body to supply oxygen and nutrients to tissues.",
CirculatorySystem: "The system responsible for transporting blood and lymph throughout the body.",
Class: "A taxonomic category that ranks above order and below phylum.",
Clone: "A genetically identical copy of an organism, produced asexually.",
Codominant: "A genetic condition in which both alleles in a heterozygous organism are fully expressed in the phenotype.",
ColdBlooded: "An animal whose body temperature changes with its environment.",
Conception: "The process of fertilization, where a sperm cell joins an egg cell.",
Copulate: "To engage in sexual reproduction.",
Cytoplasm: "The fluid within a cell that surrounds the nucleus and contains organelles.",
Digestion: "The process of breaking down food into simpler molecules for absorption.",
Diploid: "A cell or organism containing two sets of homologous chromosomes.",
Division: "A taxonomic rank used in the classification of plants, equivalent to a phylum in animals.",
DNA: "Deoxyribonucleic Acid (DNA) The molecule that carries genetic information in living organisms.",
Dominant: "A genetic trait that is expressed even when only one copy of the allele is present.",
Dorsal: "Relating to the back or upper side of an organism.",
Ecosystem: "A community of organisms interacting with each other and their environment.",
Egg: "A female reproductive cell, or ovum, capable of being fertilized.",
Embryo: "An early stage of development in multicellular organisms.",
Environment: "The external surroundings that influence an organism's growth and behavior.",
Enzyme: "A protein that speeds up chemical reactions in living organisms.",
Epidermis: "The outermost layer of skin or cells in an organism.",
Evolution: "The process by which species gradually change over generations through natural selection.",
Excretion: "The process of eliminating waste materials from an organism.",
Fermentation: "A chemical process in which microorganisms break down substances, often producing energy without oxygen.",
Fertilization: "The fusion of a sperm and an egg cell to form a zygote.",
Flower: "The reproductive structure of flowering plants.",
Fetus: "A developing mammal after the embryonic stage, typically from two months until birth in humans.",
FoodChain: "A sequence of organisms in an ecosystem where each one is a source of energy for the next.",
Fossil: "The preserved remains or traces of ancient organisms.",
Fruit: "The mature ovary of a flowering plant, often containing seeds.",
Fungus: "A kingdom of organisms that lack chlorophyll and obtain nutrients by decomposing organic material.",
Gamete: "A reproductive cell (sperm or egg) that contains half the normal number of chromosomes.",
Gene: "A segment of DNA that codes for a specific protein and determines hereditary traits.",
Genus: "A taxonomic category ranking above species and below family.",
Germination: "The process by which a seed develops into a new plant.",
Gestation: "The period of development from conception to birth in mammals.",
Gland: "An organ that produces and secretes substances like hormones or enzymes.",
Gonad: "A reproductive organ (testis or ovary) that produces gametes.",
Growth: "The increase in size or number of cells in an organism over time.",
Haploid: "A cell or organism with a single set of chromosomes, typically found in gametes.",
Heredity: "The transmission of genetic traits from parents to offspring.",
Hermaphrodite: "An organism that has both male and female reproductive organs.",
Hormone: "A chemical messenger produced by glands that regulates various bodily functions.",
Hybrid: "An organism resulting from the crossbreeding of different species or genetic varieties.",
ImmuneSystem: "The body's defense system against infections and diseases.",
Ingestion: "The process of taking in food or drink into the body.",
Instinct: "An inborn pattern of behavior that occurs naturally in response to stimuli.",
Invertebrate: "An animal without a backbone.",
Iris: "The colored part of the eye that controls the size of the pupil.",
Joint: "The point where two bones meet, allowing movement.",
Kidney: "An organ that filters waste from the blood and produces urine.",
Kingdom: "The highest taxonomic rank used in the classification of organisms.",
Larva: "An immature stage of development in some animals, usually different in form from the adult.",
Lateral: "Relating to the side of an organism or body part.",
LifeCycle: "The series of stages an organism goes through from birth to reproduction to death.",
Ligament: "A band of tissue that connects bones or supports organs.",
Liver: "A vital organ that detoxifies chemicals, metabolizes nutrients, and produces bile.",
Lungs: "Organs responsible for gas exchange, bringing oxygen into the body and expelling carbon dioxide.",
Meiosis: "A type of cell division that reduces chromosome number by half, producing gametes.",
Membrane: "A thin layer of tissue that covers a surface or separates spaces.",
Metabolism: "The set of chemical reactions that occur within an organism to maintain life.",
Microorganism: "A tiny living organism, such as bacteria or fungi, that can only be seen under a microscope.",
Mitosis: "A type of cell division that results in two identical daughter cells.",
Molecule: "The smallest unit of a chemical compound that retains its properties.",
Muscle: "A tissue that contracts to produce movement in the body.",
Mutation: "A change in the genetic sequence of an organism, which can lead to variations in traits.",
Nerve: "A bundle of fibers that transmits signals between the brain and the body.",
Neurotransmitter: "A chemical that transmits signals between nerve cells.",
Nucleus: "The organelle in a cell that contains genetic material (DNA) and controls cell functions.",
Nutrient: "A substance essential for growth, energy, and overall health in an organism.",
Omnivore: "An organism that eats both plants and animals.",
Organ: "A group of tissues working together to perform a specific function in the body.",
Organism: "Any living thing, from bacteria to humans.",
Ovary: "The female reproductive organ that produces eggs and hormones.",
Oxygen: "A gas essential for respiration in most living organisms.",
Parasite: "An organism that lives on or inside another organism and derives nutrients at the host’s expense.",
Pathogen: "A microorganism, such as a virus or bacteria, that causes disease.",
Photosynthesis: "The process by which plants convert sunlight into energy.",
Placenta: "An organ in pregnant mammals that nourishes and maintains the fetus.",
Plasma: "The liquid portion of blood that carries cells and nutrients.",
Pollination: "The transfer of pollen from one flower to another, enabling fertilization.",
Predator: "An organism that hunts and consumes other organisms for food.",
Protein: "A macromolecule made of amino acids essential for growth and repair in organisms.",
Puberty: "The stage of human development where sexual maturity is reached.",
Pupil: "The opening in the eye that controls the amount of light entering.",
Quadriceps: "A large muscle group at the front of the thigh, responsible for extending the leg.",
Reproduction: "The biological process by which new organisms are produced.",
Respiration: "The process of breaking down glucose to release energy.",
Ribosome: "A cell structure that synthesizes proteins.",
RNA: "Ribonucleic Acid (RNA) A molecule involved in protein synthesis and gene expression.",
Saliva: "A digestive fluid produced in the mouth that helps break down food.",
SkeletalSystem: "The system of bones that supports and protects the body.",
Species: "A group of similar organisms capable of interbreeding and producing fertile offspring.",
SpinalCord: "A bundle of nerves running down the back that transmits signals between the brain and body.",
Stimulus: "A change in the environment that triggers a response in an organism.",
Symbiosis: "A close and often long-term interaction between two different species.",
Tendon: "A flexible but strong tissue that connects muscles to bones.",
Tissue: "A group of similar cells working together to perform a function.",
Transpiration: "The process by which plants release water vapor through their leaves.",
TrophicLevel: "A position in a food chain that indicates an organism’s energy source.",
Urea: "A waste product formed in the liver and excreted in urine.",
Uterus: "The organ in female mammals where the embryo develops during pregnancy.",
UrinarySystem: "The system responsible for filtering waste from the blood and producing urine.",
Vaccine: "A substance used to stimulate the immune system and provide immunity to diseases.",
VascularSystem: "A network of vessels (such as blood or lymph vessels) that transport fluids throughout the body.",
Vein: "A blood vessel that carries blood toward the heart.",
Vertebrae: "The bones that form the backbone.",
Virus: "A microscopic infectious agent that replicates only inside a living host cell.",
Vitamins: "Organic compounds essential for normal growth and metabolism.",
WBC: "WhiteBloodCell (WBC) A type of blood cell that helps fight infections and diseases.",
WaterCycle: "The continuous movement of water through the environment, including evaporation, condensation, and precipitation.",
Xylem: "A tissue in plants that transports water and nutrients from the roots to the leaves.",
Yeast: "A type of fungus used in fermentation and baking.",
Yolk: "The nutrient-rich part of an egg that provides food for a developing embryo.",
Zygote: "A fertilized egg cell that will develop into an embryo.",
Zooplankton: "Microscopic aquatic animals that drift in water and serve as food for larger organisms.",

// Chemnistry Dictionary

ACID: 'A substance that releases hydrogen ions in water, tastes sour, is corrosive, has a pH below 7, and turns litmus paper red.',
ALCOHOL:'A flammable liquid (C₂H₅OH) made by fermenting sugars, used in drinks, solvents, and chemical production.',
ALKALI: 'A base that dissolves in water.',
/* ALKALI METAL: A highly reactive metal from Group 1 of the periodic table (e.g., lithium, sodium, potassium).
 *//* ALKALINE EARTH METAL: A reactive metal from Group 2 of the periodic table (e.g., magnesium, calcium).
 */ALKANE: 'A hydrocarbon with only single bonds, following the formula CₙH₂ₙ₊₂.',
ALLOTROPE: 'Different physical forms of the same element (e.g., diamond and graphite for carbon).',
ALLOY: 'A mixture of metals (or metals with nonmetals) with different properties than pure metals (e.g., steel, brass).',
/* AMINO ACID: A compound with amino (-NH₂) and carboxyl (-COOH) groups, building blocks of proteins.
 */ANALYSIS: 'Breaking a substance into its components to identify and measure them.',
ANION: "A negatively charged ion; an ion that is attracted to the anode during electrolysis.",
ANODE: "The positive electrode in an electrolytic cell.",
ATOM: "The smallest quantity of an element that can take part in a chemical reaction.",
ATOMICMASS: "The mass of an isotope of an element in atomic mass units.",
ATOMICNUMBER: "The number of protons in the nucleus of an atom of an element.",
BASE: "The main ingredient of a mixture.",
/* BOILING POINT: "The temperature at which a liquid boils at a given pressure, usually atmospheric pressure at sea level.",
 */BOND: "Something that binds, fastens, or holds together, such as a chemical linkage between atoms.",
/* BROWNIAN MOTION: "Random movement of microscopic particles suspended in a fluid, caused by bombardment of the particles by molecules of the fluid."
 */CARBOHYDRATE: "A large group of organic compounds, including sugars and polysaccharides, that serve as an important source of food and energy for animals.",
CATALYST: "A substance that increases the rate of a chemical reaction without itself suffering any permanent chemical change.",
CATHODE: "The negative electrode in an electrolytic cell.",
CATION: "A positively charged ion; an ion that is attracted to the cathode during electrolysis.",
CHAIN: "Two or more atoms or groups bonded together in a sequence.",
CHEMICALEQUATION: "A representation of a chemical reaction using symbols of the elements to indicate the amount of substance involved.",
CHAINREACTION: "A process in which a neutron colliding with an atomic nucleus causes fission, leading to a self-sustaining series of reactions.",
CHROMATOGRAPHY: "A technique for separating and analyzing the components of a mixture based on differential adsorption.",
COMBUSTION: "A chemical process in which a substance reacts with oxygen to produce heat and light.",
COMPOUND: "A substance that contains atoms of two or more chemical elements held together by chemical bonds.",
CONCENTRATED: "Having had water removed to increase concentration.",
CONDENSATION: "A reaction in which two organic molecules combine to form a larger molecule along with a simple byproduct such as water.",
CORROSION: "A process in which a solid, especially a metal, is eaten away and changed by a chemical action, as in the oxidation of iron.",
/* COVALENT BOND: "A type of chemical bond involving the sharing of electrons between atoms in a molecule."
 */CRYSTAL: "A solid substance with a regular shape in which atoms, ions, or molecules are arranged in a definite pattern.",
CRYSTALLIZATION: "The process by which crystals are formed from a liquid or a solution.",
DIFFUSION: "The movement of particles from an area of higher concentration to an area of lower concentration.",
DILUTE: "A solution that has a low concentration of solute or has been reduced in concentration.",
DISTILLATION: "The process of evaporating or boiling a liquid and condensing its vapor to separate components.",
ELECTRODE: "An element in a semiconducting device that emits, collects, or controls the movemt of electrons.",
ELECTROLYSIS: "The conduction of electricity by a solution or melt, inducing chemical changes.",
ELECTRON: "A stable elementary particle with a negative charge, found in all atoms and orbiting the nucleus.",
ELECTROVALENCY: "The valency of a substance in forming ions, equal to the number of electrons gained or lost.",
ELEMENT: "Any of the 118 known substances consisting of atoms with the same number of protons in their nuclei.",
EMULSION: "A light-sensitive coating on a base, such as paper or film, containing fine grains of silver bromide suspended in gelatin.",
ESTER: "A compound produced by the reaction between acids and alcohols with the elimination of water, often having a fragrant odor.",
ETHER: "A colorless volatile highly flammable liquid with a characteristic sweetish odor, used as a solvent and anesthetic.",
EVAPORATION: "The change of a liquid to a vapor, caused by an increase in temperature or a decrease in pressure.",
FAT: "A class of naturally occurring soft greasy solids that serve as an energy reserve in living organisms.",
FERMENTATION: "A chemical reaction in which a ferment causes an organic molecule to split into simpler substances, often producing alcohol.",
FISSION: "The act or process of splitting or breaking into parts, such as nuclear fission.",
GAS: "A substance that expands indefinitely to fill any container, with particles in rapid motion.",
HYDROCARBON: "An organic compound containing only carbon and hydrogen.",
ION: "An electrically charged atom or group of atoms formed by the loss or gain of electrons.",
MOLECULE: "The simplest unit of a chemical compound that can exist independently.",
NEUTRON: "A neutral elementary particle found in atomic nuclei.",
NUCLEUS: "The central part of an atom, containing protons and neutrons.",
OXIDATION: "A process in which a substance combines with oxygen, often producing energy.",
PERIODICTABLE: "A table of elements arranged in order of increasing atomic number, highlighting their chemical properties.",
PH: "A measure of the acidity or alkalinity of a solution, where 7 is neutral, lower values are acidic, and higher values are alkaline.",
POLYMER: "A large molecule composed of repeating structural units.",
PROTON: "A stable, positively charged elementary particle found in atomic nuclei.",
RADIOACTIVITY: "The spontaneous emission of radiation from atomic nuclei.",
SATURATED: "Containing the maximum amount of solute that can be dissolved at a given temperature and pressure.",
SOLUTION: "A homogeneous mixture of two or more substances.",
SOLVENT: "A liquid capable of dissolving another substance.",
VALENCY: "The ability of an atom to combine with other atoms, determined by the number of electrons it can lose, gain, or share." ,
};


export default scienceTerms;