const scienceTerms = {
    // Physics - Mechanics
    ACCELERATION: "The rate of change of velocity over time. Formula: a = Δv/Δt",
    FORCE: "A push or pull that can change an object's motion or shape. Formula: F = ma",
    VELOCITY: "The speed of an object in a specific direction. Formula: v = Δx/Δt",
    MOMENTUM: "The quantity of motion of a moving body. Formula: p = mv",
    INERTIA: "The resistance of an object to changes in its state of motion",
    WORK: "The transfer of energy when a force moves an object. Formula: W = Fd",
    ENERGY: "The ability to do work or cause change. It can't be created or destroyed, only transformed",
    PRESSURE: "Force applied per unit area. Formula: P = F/A",
    DENSITY: "Mass per unit volume of a substance. Formula: ρ = m/V",
    FRICTION: "Force that opposes motion between surfaces in contact",
    GRAVITY: "The force of attraction between all masses in the universe. Formula: F = G(m₁m₂)/r²",
    TORQUE: "Rotational force. Formula: τ = r × F",
    ELASTICITY: "Property of returning to original shape after deformation",
    CENTRIPETAL: "Force directing motion in circular path. Formula: F = mv²/r",
    WAVES: "A disturbance that transfers energy through matter or space",
    WAVELENGTH: "Distance between wave peaks. Formula: λ = v/f",
    FREQUENCY: "Wave cycles per second. Formula: f = 1/T",
    AMPLITUDE: "Maximum displacement from equilibrium position",
    REFLECTION: "Bouncing back of waves from a surface",
    REFRACTION: "Bending of waves passing between media",
    INTERFERENCE: "Combination of waves to form resultant wave",
    LIGHT: "Electromagnetic radiation visible to human eye",
    OPTICS: "Study of light behavior and properties",
    DIFFRACTION: "Bending of waves around obstacles",
    POLARIZATION: "Restriction of wave oscillation to one plane",
    DOPPLER: "Change in wave frequency due to relative motion",
    HEAT: "Transfer of thermal energy between objects",
    TEMPERATURE: "Measure of average kinetic energy of particles",
    THERMODYNAMICS: "Study of heat, energy, and their relationships",
    ENTROPY: "Measure of disorder in a system. Formula: ΔS = Q/T",
    HEATCAPACITY: "Heat needed to raise temperature by one degree",
    LATENT: "Heat absorbed/released during phase change",
    CONDUCTION: "Heat transfer through direct contact",
    CONVECTION: "Heat transfer through fluid movement",
    RADIATION: "Heat transfer through electromagnetic waves",
    CARNOT: "Ideal heat engine cycle efficiency. Formula: η = 1 - Tc/Th",
    QUANTUM: "Smallest possible discrete unit of any physical property",
    RELATIVITY: "Einstein's theory relating space, time, mass, and energy",
    NUCLEARREACTION: "Process changing atomic nuclei structure",
    PARTICLEPHYSICS: "Study of fundamental particles and interactions",
    PLANCK: "Quantum of action in physics. Formula: E = hf",
    UNCERTAINTY: "Heisenberg's principle of position-momentum uncertainty",
    SUPERPOSITION: "Quantum state existing in multiple states simultaneously",
    ENTANGLEMENT: "Quantum correlation between particles",
    ANTIMATTER: "Matter with opposite properties of normal matter",
    BLACKHOLE: "Region where gravity prevents light escape",
    GALAXY: "Large system of stars bound by gravity",
    NEBULA: "Cloud of gas and dust where stars form",
    SUPERNOVA: "Explosive death of massive star",
    PLANET: "Celestial body orbiting a star",
    ASTEROID: "Rocky object orbiting the Sun",
    COMET: "Icy body that produces gas tail near Sun",
    METEOR: "Space rock burning in Earth's atmosphere",
    PULSAR: "Rotating neutron star emitting radiation",
    QUASAR: "Very bright galactic nucleus",
    REDSHIFT: "Wavelength increase from moving objects",
    ATOM: "The basic unit of matter, made up of protons, neutrons, and electrons",
    MOLECULE: "Group of atoms bonded together",
    ELEMENT: "Pure substance made of one type of atom",
    COMPOUND: "Substance made of different elements chemically combined",
    REACTION: "Process where substances change into new substances",
    SOLUTION: "Homogeneous mixture of substances",
    ACID: "Substance that produces H+ ions in solution",
    BASE: "Substance that produces OH- ions in solution",
    CATALYST: "Substance that speeds up a reaction without being consumed",
    BOND: "Force holding atoms together in molecules",
    ELECTRON: "Negatively charged particle in atoms",
    PROTON: "Positively charged particle in atomic nuclei",
    NEUTRON: "Neutral particle in atomic nuclei",
    CELL: "Basic unit of life",
    DNA: "Molecule carrying genetic instructions",
    RNA: "Molecule involved in protein synthesis",
    GENE: "Unit of heredity",
    PROTEIN: "Large molecules essential for life processes",
    ENZYME: "Protein that catalyzes biological reactions",
    NUCLEUS: "Control center of the cell",
    MEMBRANE: "Barrier around cells and organelles",
    CHROMOSOME: "Structure containing DNA",
    MITOSIS: "Cell division for growth and repair",
    ATMOSPHERE: "Gaseous layer surrounding Earth",
    LITHOSPHERE: "Rigid outer part of Earth",
    HYDROSPHERE: "All water on Earth",
    BIOSPHERE: "All life on Earth",
    CLIMATE: "Long-term weather patterns",
    WEATHER: "Short-term atmospheric conditions",
    EROSION: "Process of wearing away Earth's surface",
    MINERAL: "Naturally occurring inorganic solid"
};

export default scienceTerms;