const scienceTerms = {

    A: "ADMIN POWER!!!!!!!!!!!!!!!",
    E: "ADMIN POWER!!!!!!!!!!!!!!!",
    I: "ADMIN POWER!!!!!!!!!!!!!!!",
    O: "ADMIN POWER!!!!!!!!!!!!!!!",
    U: "ADMIN POWER!!!!!!!!!!!!!!!",

    ACCELERATION: "The rate of change of an object's velocity.",
    ATOM: "The basic unit of matter, consisting of protons, neutrons, and electrons.",
    CAPACITOR: "A device used to store electrical energy in an electric field.",
    CONSERVATIONOFENERGY: "A principle stating that energy cannot be created or destroyed, only transferred or transformed.",
    CURRENTS: "The flow of electric charge through a conductor.",
    DENSITY: "The mass per unit volume of a substance.",
    ELECTRICFIELD: "A field surrounding charged particles that exerts a force on other charged particles.",
    ENERGY: "The capacity to do work or cause change.",
    FORCE: "An influence that causes an object to change its motion or shape.",
    GRAVITATIONALFORCE: "The force of attraction between two masses, proportional to their masses and inversely proportional to the square of the distance between them.",
    HEAT: "The transfer of thermal energy from one body to another.",
    INERTIA: "The resistance of an object to a change in its state of motion.",
    MAGNETICFIELD: "A field produced by moving electric charges, influencing the behavior of other charges in the field.",
    MOMENTUM: "The product of an object's mass and velocity, indicating its motion.",
    OPTICS: "The study of light and its interactions with matter.",
    PULSE: "A rapid fluctuation or wave of energy.",
    QUANTUM: "A discrete quantity of energy proportional in magnitude to the frequency of the radiation it represents.",
    RELATIVITY: "A theory by Einstein describing the relationship between space and time.",
    THERMODYNAMICS: "The branch of physics that deals with the relations between heat, work, temperature, and energy.",
    WAVES: "Oscillations that transfer energy through a medium or space, such as light or sound waves.",
    AMPLITUDE: "The maximum extent of a vibration or oscillation.",
    BLACKBODY: "An idealized object that absorbs all radiation and emits a characteristic spectrum.",
    CAPACITANCE: "The ability of a system to store charge per unit voltage.",
    COULOMB: "The unit of electric charge.",
    FRICTION: "The force that resists the relative motion of two objects in contact.",
    GALVANOMETER: "A device used to measure small electrical currents.",
    HEATCAPACITY: "The amount of heat required to raise the temperature of an object by one degree Celsius.",
    INTERFERENCE: "The phenomenon in which two or more waves overlap and combine to form a new wave pattern.",
    LIGHT: "Electromagnetic radiation that can be perceived by the human eye.",
    MAGNETISM: "A physical phenomenon produced by the motion of electric charge, resulting in attractive and repulsive forces.",
    MATTER: "Anything that has mass and occupies space.",
    NUCLEARREACTION: "A process that alters the composition of an atom's nucleus.",
    OHMSLAW: "A law that states the relationship between voltage, current, and resistance in an electrical circuit.",
    PARALLAX: "The apparent shift in the position of an object when viewed from two different perspectives.",
    PRESSURE: "The force exerted per unit area of a surface.",
    PROTON: "A subatomic particle with a positive charge, found in the nucleus of an atom.",
    QUARK: "A fundamental particle that makes up protons and neutrons.",
    RADAR: "A system used to detect objects and measure their distance by bouncing radio waves off them.",
    REFLECTION: "The change in direction of a wave when it bounces off a surface.",
    REFRACTION: "The bending of light as it passes through different media.",
    RENEWABLEENERGY: "Energy obtained from natural sources that can be replenished.",
    RESISTANCE: "The opposition to the flow of electric current.",
    SUPERCONDUCTOR: "A material that can conduct electricity with zero resistance when cooled to very low temperatures.",
    THERMALCONDUCTIVITY: "The ability of a material to conduct heat.",
    TRANSITIONELEMENTS: "Elements found in the middle of the periodic table, often forming colored compounds.",
    UNITS: "Standardized quantities used to measure physical properties.",
    VELOCITY: "The speed of an object in a particular direction.",
    WAVELENGTH: "The distance between two consecutive crests or troughs of a wave.",
    WORK: "The transfer of energy when a force is applied to move an object over a distance.",
    XRAYS: "High-energy electromagnetic radiation used in medical imaging.",
    YIELD: "The amount of a product formed in a chemical or physical process.",
    ZEROTHLAW: "A principle stating that if two systems are each in thermal equilibrium with a third system, they are in thermal equilibrium with each other.",
    AMPERAGE: "The strength of an electric current.",
    BOLTZMANNCONSTANT: "A physical constant relating the average kinetic energy of particles in a gas to the temperature.",
    CHARGE: "The property of matter responsible for electric phenomena.",
    ELECTRON: "A subatomic particle with a negative charge, found in electron shells around an atom's nucleus.",
    FIELD: "A region in space where a force can be experienced by a mass or charge.",
    FUSION: "A process in which two atomic nuclei combine to form a larger nucleus, releasing energy.",
    GAMMARAYS: "Electromagnetic radiation of the highest frequency and energy.",
    HERTZ: "The unit of frequency, equal to one cycle per second.",
    IONIZATION: "The process of removing one or more electrons from an atom or molecule.",
    KINETICENERGY: "Energy possessed by an object due to its motion.",
    LUMINESCENCE: "The emission of light from a substance not resulting from heat.",
    MAGNETOMETER: "An instrument used to measure magnetic fields.",
    MOLECULARWEIGHT: "The weight of a molecule, calculated by adding the atomic weights of all atoms in the molecule.",
    NUCLEARFISSION: "A process in which a heavy nucleus splits into two smaller nuclei, releasing energy.",
    OPTICALFIBER: "A thin fiber made of glass or plastic used to transmit light signals.",
    POLARIZATION: "The orientation of the oscillations in a wave, often referring to light waves.",
    QUANTUMMECHANICS: "The branch of physics dealing with the behavior of particles on the atomic and subatomic level.",
    RELUCTANCE: "The opposition to the magnetic flux in a magnetic circuit.",
    SOLARFLARE: "A sudden burst of energy from the sun's surface.",
    TENSILESTRENGTH: "The maximum stress a material can withstand while being stretched or pulled before breaking.",
    UNIFIEDFIELDTHEORY: "A theoretical framework aiming to explain all fundamental forces of nature in a single equation.",
    ACID: "A substance that donates protons or accepts electrons in reactions.",
    BASE: "A substance that accepts protons or donates electrons.",
    CATALYST: "A substance that increases the rate of a chemical reaction without being consumed in the process.",
    CHEMICALBOND: "An interaction between atoms that holds them together in a molecule.",
    CONCENTRATION: "The amount of a substance in a given volume of solution.",
    ELEMENT: "A pure substance made up of only one type of atom.",
    ENZYME: "A protein that accelerates chemical reactions in biological processes.",
    ELECTROLYTE: "A substance that conducts electricity when dissolved in water.",
    EVAPORATION: "The process of a liquid turning into vapor, typically at the surface of the liquid.",
    ION: "An atom or molecule with a net electric charge due to the loss or gain of one or more electrons.",
    ISOTOPES: "Atoms of the same element with different numbers of neutrons.",
    METAL: "Elements that are typically shiny, good conductors of heat and electricity.",
    MOLECULE: "Two or more atoms bonded together chemically.",
    OXIDATION: "A process in which an atom loses electrons during a chemical reaction.",
    PERIODICTABLE: "A table of chemical elements arranged by their atomic number and properties.",
    PH: "A measure of the acidity or alkalinity of a solution.",
    POLARITY: "A characteristic of molecules in which there is an uneven distribution of charge.",
    REDUCTION: "A process in which an atom gains electrons during a chemical reaction.",
    SOLVENT: "A substance that dissolves a solute to form a solution.",
    VISCOSITY: "The resistance of a fluid to flow.",
    ALKALINE: "A solution with a pH greater than 7, basic in nature.",
    ATOMICNUMBER: "The number of protons in the nucleus of an atom, determining its chemical properties.",
    BONDING: "The process of forming chemical bonds between atoms.",
    CALORIMETER: "An instrument used to measure the heat of chemical reactions.",
    CONDUCTIVITY: "A material's ability to conduct electricity or heat.",
    CONDENSATION: "The process by which a gas turns into a liquid.",
    ASTRONOMICALUNIT: "A unit of distance equal to the average distance between the Earth and the Sun, approximately 93 million miles.",
    BLACKHOLE: "A region of space where the gravitational pull is so strong that not even light can escape.",
    COMET: "A small icy body that orbits the Sun and has a characteristic tail of gas and dust.",
    CONSTELLATION: "A group of stars forming a recognizable pattern, often named after mythological figures or animals.",
    ECLIPSE: "An event where one celestial body moves into the shadow of another.",
    GALAXY: "A vast system of stars, gas, dust, and dark matter, bound together by gravity.",
    GRAVITATIONALWAVES: "Ripples in spacetime caused by the acceleration of massive objects, such as colliding black holes.",
    LIGHTYEAR: "The distance that light travels in one year, approximately 5.88 trillion miles.",
    METEOR: "A small rock or particle from space that burns up in Earth's atmosphere, creating a streak of light.",
    MOON: "A natural satellite that orbits a planet, often large relative to the planet it orbits.",
    NEBULA: "A large cloud of gas and dust in space, often a birthplace of stars.",
    NOVA: "A sudden, dramatic increase in the brightness of a star, often due to a thermonuclear explosion.",
    PLANET: "A celestial body that orbits a star, is spherical in shape, and has cleared its orbit of other debris.",
    QUASAR: "A very energetic and distant active galactic nucleus, powered by a supermassive black hole.",
    STAR: "A luminous sphere of plasma held together by gravity, undergoing nuclear fusion in its core.",
    SUPERNOVAE: "An explosion of a massive star, releasing an immense amount of energy.",
    ASTEROID: "A small rocky body that orbits the Sun, mostly found in the asteroid belt between Mars and Jupiter.",
    COSMOLOGY: "The study of the origin, evolution, and eventual fate of the universe.",
    DARKMATTER: "A type of matter that does not emit light or energy, detectable only through its gravitational effects.",
    DARKENERGY: "A mysterious force that is thought to drive the accelerated expansion of the universe.",
    EXOPLANET: "A planet that orbits a star outside of our solar system.",
    FALLOFF: "The reduction in intensity of light or radiation as it spreads through space.",
    GALACTICCENTER: "The rotational center of a galaxy, typically containing a supermassive black hole.",
    HORIZON: "The boundary in space beyond which events cannot affect an observer.",
    HUBBLEDEEPFIELD: "An image of a small region of space taken by the Hubble Space Telescope, revealing thousands of galaxies.",
    INTERSTELLARMEDIUM: "The matter that exists in the space between stars in a galaxy.",
    KARMANLINE: "The boundary of space, generally considered to be 100 kilometers above Earth's surface.",
    LUNAR: "Relating to the Moon.",
    NEUTRONSTAR: "A compact star that remains after a supernova explosion, composed mainly of neutrons.",
    ORBIT: "The curved path of a celestial body as it moves around another object due to gravitational forces.",
    PARALLAX: "The apparent shift in the position of a star due to the motion of the observer.",
    PULSAR: "A rotating neutron star that emits beams of radiation, observable as pulses.",
    REDSHIFT: "The phenomenon in which light from distant galaxies appears redder, indicating they are moving away from Earth.",
    SATELLITE: "A natural or artificial object that orbits a planet or a star.",
    SOLARFLARE: "A sudden burst of energy from the Sun's surface, often releasing radiation and particles into space.",
    STELLAREVOLUTION: "The process by which a star changes over time, from formation to its ultimate fate.",
    SUPERGIANT: "An extremely large star that is much brighter and larger than the Sun.",
    WHITEHOLE: "A theoretical region of space that ejects matter and energy, the opposite of a black hole.",
    ASTRONOMICALOBSERVATORY: "A facility used for observing celestial objects, often equipped with telescopes and other instruments.",
    CIRCULARORBIT: "An orbit in which a celestial body follows a circular path around another object.",
    CONSTELLATIONBOUNDARY: "The defined area of the sky that a specific constellation occupies.",
    EARTHSAXIS: "The imaginary line through the Earth around which it rotates, tilted at 23.5 degrees.",
    EQUATOR: "An imaginary line around the Earth, equidistant from the poles, dividing the planet into northern and southern hemispheres.",
    EXTRASOLAR: "Relating to objects or phenomena outside of our solar system.",
    FAINTOBJECT: "An astronomical object that is too dim to be seen with the naked eye.",
    FISSION: "The splitting of an atomic nucleus, often releasing energy, used in stars as a source of power.",
    GALACTICPLANE: "The flat, disk-like region of a galaxy, containing most of the stars and interstellar matter.",
    GASGIANT: "A large planet composed mostly of hydrogen and helium, such as Jupiter or Saturn.",
    GLOWINGNEBULA: "A nebula that emits light due to the ionization of gas by nearby stars.",
    HEMISPHERE: "Half of a celestial body, such as the northern or southern hemisphere of Earth or the Moon.",
    HELIOSPHERE: "The bubble-like region of space dominated by the solar wind from the Sun.",
    HUBBLELAW: "A law stating that the velocity at which galaxies recede from each other is proportional to their distance.",
    HZZONE: "The region around a star where conditions may be suitable for liquid water to exist on a planet's surface.",
    INTERGALACTIC: "The space between galaxies, which is mostly empty.",
    KEPLERSLAWS: "Three laws describing the motion of planets around the Sun.",
    LAGRANGIANPOINT: "A point in space where the gravitational forces of two large bodies, such as the Earth and the Moon, balance the centripetal force of a smaller object.",
    LIGHTYEAR: "The distance that light travels in one year, approximately 5.88 trillion miles.",
    LONGITUDE: "The angular distance east or west of the Prime Meridian, often used in planetary mapping.",
    MASSIVEBLACKHOLE: "A black hole with a mass millions to billions of times that of the Sun, usually located at the center of a galaxy.",
    METEORSHOWER: "An event where numerous meteors streak through the atmosphere as a result of Earth passing through a debris field.",
    MILKYWAY: "The galaxy that contains our solar system, named for its milky, cloud-like appearance.",
    NEARBYGALAXY: "A galaxy relatively close to the Milky Way, such as the Andromeda Galaxy.",
    PARSEC: "A unit of distance used in astronomy, equal to about 3.26 light-years.",
    PLEIADES: "A famous open star cluster in the constellation Taurus, often referred to as the Seven Sisters.",
    REDGIANT: "A phase in stellar evolution where a star expands and cools after exhausting its hydrogen fuel.",
    SINGULARITY: "A point in space where the gravitational field becomes infinitely strong, such as at the center of a black hole.",
    SPECTRUM: "The range of wavelengths of light emitted by a celestial object, used to determine its composition.",
    SOLSTICE: "The two points in the Earth's orbit when the Sun is farthest from the equator, marking the longest and shortest days of the year.",
    SPIRALGALAXY: "A type of galaxy characterized by a flat disk with a central bulge and spiral arms, like the Milky Way.",
    STARCLUSTER: "A group of stars bound together by gravity, often formed from the same molecular cloud.",
    SUNSPOT: "A dark, cooler area on the Sun's surface caused by magnetic activity.",
    TIDALLOCKING: "The phenomenon where a celestial body always shows the same face to the object it orbits, such as the Moon's orbit around the Earth.",
    TWINKLING: "The rapid fluctuation in brightness of a star as its light passes through Earth's atmosphere.",
    VACUUM: "Space that is almost completely empty of matter, with no air or atmosphere.(Astronomy), A space devoid of matter, often used in experiments to eliminate air resistance.(Physics)",
    VYCANISMAJORIS: "A red supergiant star in the constellation Canis Major, one of the largest known stars.",
    WORMHOLE: "A hypothetical tunnel-like structure in spacetime that could connect distant parts of the universe.",
    ZODIAC: "The twelve constellations that lie along the Sun's apparent path through the sky over the course of a year.",
    ZENITH: "The point in the sky directly above an observer's head.",
    ZODIACALLIGHT: "A faint glow in the sky caused by sunlight reflecting off interplanetary dust particles.",
    SUN: "sdasdas",
    CHLOROPHYLLA: "A green pigment found in the chloroplasts of plants, algae, and some bacteria, essential for photosynthesis.",
    ANTIBIOTICRESISTANCE: "The ability of bacteria or other microorganisms to resist the effects of drugs that once killed them or inhibited their growth.",
    GENETICDIVERSITY: "The total number of genetic characteristics in the genetic makeup of a species, often seen as a measure of its adaptability.",
    MITOCHONDRIALDNA: "The DNA located in mitochondria that is inherited maternally and plays a role in energy production within cells.",
    ENZYMATICACTIVITY: "The catalytic activity of enzymes in accelerating chemical reactions in biological processes.",
    HORMONALBALANCE: "The state in which the levels of hormones in the body are within a range that allows optimal physiological function.",
    PHOTOSYNTHESISRATE: "The rate at which plants convert light energy, water, and carbon dioxide into glucose and oxygen, used to assess plant growth.",
    IMMUNERESPONSE: "The body's defensive reaction to pathogens, involving the immune system's activation to protect the body from infections.",
    DNAREPLICATION: "The process by which a cell copies its DNA before division to ensure that each daughter cell receives an identical copy.",
    PROTEINSYNTHESIS: "The process by which cells build proteins, which involves transcription and translation to form the final protein product.",
    GENOMICSEQUENCING: "The process of determining the sequence of nucleotides in the entire genome of an organism, used in genetic research.",
    MICROBIOMEDIVERSITY: "The variety of microorganisms present in a specific environment, such as the gut microbiome in humans.",
    NEUROTRANSMITTERS: "Chemicals that transmit signals across synapses between neurons in the brain and other parts of the body.",
    CYTOKINESTORM: "An overreaction of the immune system that leads to the release of too many cytokines, which can cause inflammation and tissue damage.",
    GENETICMUTATION: "A change in the DNA sequence that can result in a new trait or disease and may be inherited.",
    CELLULARMETABOLISM: "The complex set of chemical reactions in cells that maintains life by converting nutrients into energy.",
    ENDOPLASMICRETICULUM: "A network of membranes within the cytoplasm of eukaryotic cells involved in protein and lipid synthesis.",
    CYTOSKELETALSTRUCTURE: "The network of protein filaments and tubules that provides structural support to cells and is involved in intracellular transport.",
    PROKARYOTICCELLS: "Cells without a membrane-bound nucleus or organelles, found in organisms like bacteria and archaea.",
    IMMUNESYSTEMRESPONSE: "The response of the immune system to foreign invaders such as bacteria, viruses, and fungi.",
    HORMONALSIGNALLING: "The process through which hormones act as messengers to regulate various biological processes, including growth, metabolism, and reproduction.",
    NEUROLOGICALPATHWAYS: "The neural routes taken by nerve impulses through the brain and spinal cord to coordinate functions in the body.",
    BLOODPRESSURECONTROL: "The regulation of the force exerted by circulating blood on the walls of blood vessels, crucial for maintaining cardiovascular health.",
    CELLDIVISIONCYCLE: "The series of events that take place in a eukaryotic cell as it grows and divides to form daughter cells.",
    MOLECULARBIOLOGY: "The branch of biology that deals with the molecular basis of biological activity, focusing on DNA, RNA, and protein synthesis.",
    ANTIBODYPRODUCTION: "The process by which the immune system produces antibodies in response to the presence of pathogens.",   
};

export default scienceTerms;